services:
  db:
    container_name: secondhand-db
    image: postgres
    # restart: always
    environment:
      POSTGRES_DB: postgres # if this value is not "postgres", when connecting database with TypeORM, "database <POSTGRES_DB> does not exist" error occurs
      POSTGRES_USER: postgres # if this value is not "postgres", when connecting database with TypeORM, "role <POSTGRES_USER> does not exist" error occurs
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  pgadmin:
    container_name: secondhand-pgadmin
    image: dpage/pgadmin4
    # restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8080:80'
